name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test for "Hello World" in output
      id: test-for-hello-world-in-output
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test for "Hello World" in output
        setup-command: gcc hello.c -o hello
        command: "./hello"
        input: ''
        expected-output: Hello World
        comparison-method: contains
        timeout: 5
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-FOR-HELLO-WORLD-IN-OUTPUT_RESULTS: "${{steps.test-for-hello-world-in-output.outputs.result}}"
      with:
        runners: test-for-hello-world-in-output
